name: Test_CI
on: [push]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.2.0
      with:
        clang-format-version: '13'
        check-path: 'src'
  Test-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install cppcheck
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -y libgtest-dev valgrind cmake
      - run: sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
      - run: sudo tar -xf release-1.7.0.tar.gz
      - run: cd googletest-release-1.7.0
      - run: sudo cmake
      - run: sudo make googletest-release-1.7.0
      - run: sudo cppcheck Homework_1/get_data_by_user.c Homework_1/get_data_by_user.h Homework_1/split_logic.c Homework_1/split_logic.h Homework_1/waybill_structure.h Homework_1/main.c 
      - run: sudo cmake
      - run: valgrind --tool=memcheck --leak-check=summary --track-origins=yes --leak-check=full --error-exitcode=1 ./Homework_1/${BIN_NAME}
